services:
  - type: web
    name: dos-ensemble-api  # You can change this to any project name
    env: python
    plan: free  # Change to 'starter' or 'standard' if using paid tier
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
